import { Inter } from 'next/font/google'
import './globals.css'
import { CartProvider } from '@/app/cartContext'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Product store',
  description: 'Generated by create next app',
  head: (
    <>
      <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        integrity="sha512-2gQ9a5Nlf4Pf6+qzqeaSZb9fXxuKE0lAqmYO2nXQm6ZltC9Xe+4vN5AtMkaynK2jCuWaeMKUvxdzVc4WJR+gR3A=="
        crossOrigin="anonymous"
      />
    </>
  ),
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CartProvider>
        <body className={inter.className}>
          {children}
        </body>
      </CartProvider>
    </html>
  )
}

